name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 9 * * MON'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm test
